# src/imatools/io/parfile_io.py
"""File I/O for Meshtools3d parameter files.

Migrated from ``imatools.common.m3dutils`` (T2e).  Legacy callers that import
from ``imatools.common.m3dutils`` continue to work via the re-export shim at
the bottom of that module.

``load_from_par`` calls ``get_empty_pot`` which stays in ``m3dutils``; it is
accessed via a lazy call-time import to avoid circular-import issues at the
module level (the target may be imported before m3dutils).
"""

from __future__ import annotations


def _m3d():
    import imatools.common.m3dutils as m  # noqa: PLC0415

    return m


def load_from_par(filename: str):
    """
    Reads Meshtools3d parameter files and returns a dictionary
    """
    filename += ".par" if ".par" not in filename else ""
    with open(filename, "r", encoding="utf-8") as f:
        lines = f.readlines()

    pot = _m3d().get_empty_pot()
    current_section = ""
    for line in lines:
        if "#" in line:  # comment
            continue

        elif "[" in line:  # section
            current_section = line.strip().strip("[").strip("]")
            print(f"Reading in section {current_section}")
            continue

        elif not line.strip():  # line is empty
            continue

        elif "=" in line:
            key, value = line.split("=")
            key = key.strip()
            value = value.strip()

            pot[current_section][key] = value

    return pot


def save_pot(pot: dict, filename: str):
    with open(filename, "w") as f:
        f.write("# Meshtools3d parameter file\n")
        f.write("# Generated by imatools.m3dutils \n\n")
        for section in pot.keys():
            f.write(f"[{section}]\n")
            for key, value in pot[section].items():
                value = int(value) if isinstance(value, bool) else value
                if key == "seg_name":
                    value += ".inr" if ".inr" not in value else ""
                f.write(f"{key} = {value}\n")
            f.write("\n")
    return
